FROM node:alpine
WORKDIR '/app'

# Install yarn and other dependencies via apk
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/* && npm install -g knex

COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
