FROM node:alpine
WORKDIR '/app'

# Install yarn and other dependencies via apk
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/* && npm install -g knex

COPY ./package.json ./
COPY ./yarn.lock ./
RUN npm install -g -s --no-progress yarn && yarn
COPY . .
CMD ["npm", "run", "dev"]
